
package gov.va.sep.automatedtesting.suites;

import static org.junit.Assert.*;

import java.util.HashMap;
import java.util.Properties;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.Select;

import gov.va.sep.automatedtesting.template.*;
import gov.va.sep.automatedtesting.utils.LogbackFileUtils;

public class SEPVDCForms extends AutomatedTestingSuite {
	//private static StringBuffer verificationErrors = new StringBuffer();
	//public Properties propertyFile = getTestProperties("vet1");
	LoginTemplate loginTemp = new LoginTemplate(propertyFile);
	SearchVetTemplate searchTemp = new SearchVetTemplate(propertyFile);
	VDCFormTemplate formTemp = new VDCFormTemplate(propertyFile);
	
	@Test
	public HashMap RunAllForms() {
		try{
			strTime = System.currentTimeMillis();
			LogbackFileUtils.start(this.getClass());			
			logger.info(":: In Start of RunAllVDCForms() method");
			//r.delay(5000);
			logger.info("**********Start open application************");
			driver.get(getProperties().getProperty("URL"));
			logger.info("::getting the URL from the properties file :: The URL is ::"+getProperties().getProperty("URL"));
			r.delay(5000);
			
			//Login SEP
			SEPLoginLogout.login(loginTemp);
			r.delay(5000);

			//Perform Search by SSN
			SEPSearchVerification.searchBySSN(searchTemp);
			r.delay(5000);

			//Search Results verification and select Online Forms
			SEPSearchVerification.searchResults(searchTemp, 0);
			r.delay(18000);
			
			//Run Dependent Benefit form
			driver.switchTo().frame(0);
			createDependentBenefits(formTemp);
			//r.delay(5000);
			
			//Run Compensation Benefit form
			createCompensationBenefits(formTemp);
		    
			//driver.switchTo().frame(0);
			//Run Compensation Benefit form
			createPTSDBenefits(formTemp);
			
			//Run Compensation Benefit form
			createUnemployabilityBenefits(formTemp);
		    //r.delay(5000);
		    
		    // Go back to dashboard
		    //driver.switchTo().defaultContent();
		    //driver.findElement(By.id("dashboard")).click();	    
		    //r.delay(5000);
		    
		    //Logout
		    SEPLoginLogout.logout();		    
		    LogbackFileUtils.stop();
		    
		    return returnObj;
		}catch(Throwable e){
			logger.error("Test Failure: " + e.toString());
			closeDriver();
			endTime = System.currentTimeMillis();
			buildTestStatusObj(true);
			//LogbackFileUtils.stop();
			return returnObj;
		}	    
	}
	
	public static void deleteForm(String formName){
		//Functionality to delete open forms prior to creation
		driver.findElement(By.xpath("//table[@id='openApps']/tbody/tr[td/a[contains(text(),'" + formName  + "')]]/td[7]/a[contains(text(),'Delete')]")).click();
		r.delay(5000);
		driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	}
	public static void createDependentBenefits(VDCFormTemplate formTemp){
		//Create Dependent Benefits forms
		deleteForm("Dependent");
		driver.findElement(By.xpath("(//a[contains(text(),'Apply Now')])[1]")).click();
		logger.info("::Clicked on Dependent Benefits Form ::");
		r.delay(10000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("privacyAccepted")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.linkText("Update My Marital Status")).click();
	    r.delay(5000);
	    driver.findElement(By.id("marriageType0")).click();
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(7000);
	    driver.findElement(By.id("spouse.firstName")).clear();
	    driver.findElement(By.id("spouse.firstName")).sendKeys("GGG");
	    driver.findElement(By.id("spouse.middleName")).clear();
	    driver.findElement(By.id("spouse.middleName")).sendKeys("H");
	    driver.findElement(By.id("spouse.lastName")).clear();
	    driver.findElement(By.id("spouse.lastName")).sendKeys("CCC");
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("spouse.hasNoSsn")).click();
	    driver.findElement(By.id("spouse.dateOfBirth")).clear();
	    driver.findElement(By.id("spouse.dateOfBirth")).sendKeys("01011967");
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("spouse.veteran1")).click();
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("spouse.currentMarriage.marriageDate")).clear();
	    driver.findElement(By.id("spouse.currentMarriage.marriageDate")).sendKeys("01011980");
	    new Select(driver.findElement(By.id("spouse.currentMarriage.country.dropDownCountry"))).selectByVisibleText("USA");
	    driver.findElement(By.cssSelector("option[value=\"USA\"]")).click();
	    r.delay(2000);
	    driver.findElement(By.id("spouse.currentMarriage.city")).clear();
	    driver.findElement(By.id("spouse.currentMarriage.city")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("spouse.currentMarriage.state"))).selectByVisibleText("Virginia");
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.linkText("Add a new Dependent Child")).click();
	    r.delay(6000);
	    driver.findElement(By.id("firstName")).clear();
	    driver.findElement(By.id("firstName")).sendKeys("CCC");
	    driver.findElement(By.id("middleName")).clear();
	    driver.findElement(By.id("middleName")).sendKeys("BBB");
	    driver.findElement(By.id("lastName")).clear();
	    driver.findElement(By.id("lastName")).sendKeys("NNN");
	    //driver.findElement(By.id("childRelationshipType0")).click();
	    new Select(driver.findElement(By.id("childRelationshipType"))).selectByVisibleText("BIOLOGICAL");
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("dateOfBirth")).clear();
	    driver.findElement(By.id("dateOfBirth")).sendKeys("01012001");
	    new Select(driver.findElement(By.id("countryOfBirth.dropDownCountry"))).selectByVisibleText("USA");
	    driver.findElement(By.cssSelector("option[value=\"USA\"]")).click();
	    r.delay(2000);
	    driver.findElement(By.id("cityOfBirth")).clear();
	    driver.findElement(By.id("cityOfBirth")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("stateOfBirth"))).selectByVisibleText("Virginia");
	    driver.findElement(By.id("hasNoSsn")).click();
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.cssSelector("div.modalNav > #btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.linkText("Upload")).click();
	    driver.findElement(By.xpath("//input[@name='file']")).sendKeys(formTemp.getFileUploadPath());
	    r.delay(18000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("accept")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(30000); // possibly 18-20 secs for submission
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	}
	
	public static void createCompensationBenefits(VDCFormTemplate formTemp){
		//Create Compensation Benefit Form
		deleteForm("Compensation Benefit");
		driver.findElement(By.xpath("(//a[contains(text(),'Apply Now')])[2]")).click();
		logger.info("::Clicked on Compensation Benefits Form ::");
		r.delay(10000);
	    driver.findElement(By.id("privacyAccepted")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("vaFileNumber")).clear();
	    driver.findElement(By.id("vaFileNumber")).sendKeys("60002332");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(15000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(15000);
	    driver.findElement(By.id("informalClaimAccepted")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(8000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.linkText("Add a New Period of Service")).click();
	    r.delay(6000);
	    new Select(driver.findElement(By.id("serviceBranch"))).selectByVisibleText("Public Health Service");
	    driver.findElement(By.id("activeDutyBegin")).clear();
	    driver.findElement(By.id("activeDutyBegin")).sendKeys("01012002");
	    driver.findElement(By.id("activeDutyEnd")).clear();
	    driver.findElement(By.id("activeDutyEnd")).sendKeys("01012003");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("separationLocation")).clear();
	    driver.findElement(By.id("separationLocation")).sendKeys("Lackland");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.linkText("Claim a New Disability")).click();
	    r.delay(6000);
	    driver.findElement(By.xpath("//span[@onclick=\"disabilityFill('ankle strain', 400)\"]")).click();
	    r.delay(2000);
	    new Select(driver.findElement(By.id("specialIssue"))).selectByVisibleText("38 USC 1151");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("receivedTreatment2")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.linkText("Add a Treatment Record")).click();
	    r.delay(5000);
	    driver.findElement(By.id("startTreatment")).clear();
	    driver.findElement(By.id("startTreatment")).sendKeys("05012002");
	    r.delay(3000);
	    driver.findElement(By.id("endTreatment")).clear();
	    driver.findElement(By.id("endTreatment")).sendKeys("06012002");
	    r.delay(3000);
	    new Select(driver.findElement(By.id("treatmentCenterState"))).selectByVisibleText("Virginia");
	    r.delay(3000);
	    new Select(driver.findElement(By.id("corpTreatmentId"))).selectByVisibleText("HAMPTON VA MEDICAL CENTER");
	    r.delay(3000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    new Select(driver.findElement(By.id("accountType"))).selectByVisibleText("Checking");
	    r.delay(1000);
	    driver.findElement(By.id("routingNumber")).clear();
	    driver.findElement(By.id("routingNumber")).sendKeys("121122676");
	    r.delay(3000);
	    driver.findElement(By.id("maskedAccountNumber")).clear();
	    driver.findElement(By.id("maskedAccountNumber")).sendKeys("23344567789");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    //driver.findElement(By.id("cond3")).click();
	    driver.findElement(By.id("cond0")).click();
	    //driver.findElement(By.id("cond2")).click();
	    //driver.findElement(By.id("cond4")).click();
	    //driver.findElement(By.id("cond1")).click();
	    //driver.findElement(By.id("cond5")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    //driver.findElement(By.id("circumstanceNeeded1")).click();
	    //driver.findElement(By.id("btnNext")).click();
	    //driver.findElement(By.id("circumstanceNeeded1")).click();
	    //driver.findElement(By.id("btnNext")).click();
	    //driver.findElement(By.id("circumstanceNeeded1")).click();
	    //driver.findElement(By.id("btnNext")).click();
	    driver.findElement(By.xpath("//a[@id='btnUpload' and contains(@href,'uploadDoc&i=1')]")).click();
	    r.delay(5000);
	    new Select(driver.findElement(By.id("attachments[0].attachmentType"))).selectByVisibleText("Application for Compensation for Unemployability");
	    driver.findElement(By.xpath("//input[@type='file']")).sendKeys(formTemp.getFileUploadPath());
	    r.delay(5000);
	    driver.findElement(By.xpath("//input[@type='submit']")).click();
	    r.delay(18000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();	
	    r.delay(5000);
	}
	
	public static void createPTSDBenefits(VDCFormTemplate formTemp){
		// Create PTSD Forms
		deleteForm("PTSD");
		driver.findElement(By.xpath("(//a[contains(text(),'Apply Now')])[5]")).click();
		logger.info("::Clicked on PTSD Benefits Form ::");
		r.delay(10000);
	    driver.findElement(By.id("formInfo.privacyAccepted")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("fileNumber")).clear();
	    driver.findElement(By.id("fileNumber")).sendKeys("60002332");
	    //driver.findElement(By.id("noFileNumber")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(15000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(12000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.linkText("* Add an Incident")).click();
	    r.delay(5000);
	    new Select(driver.findElement(By.id("dateOfIncident.month"))).selectByVisibleText("January");
	    new Select(driver.findElement(By.id("dateOfIncident.day"))).selectByVisibleText("01");
	    driver.findElement(By.id("dateOfIncident.year")).clear();
	    driver.findElement(By.id("dateOfIncident.year")).sendKeys("2001");
	    driver.findElement(By.id("location.city")).clear();
	    driver.findElement(By.id("location.city")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("location.state"))).selectByVisibleText("Virginia");
	    driver.findElement(By.id("location.landmark")).clear();
	    driver.findElement(By.id("location.landmark")).sendKeys("YMCA");
	    new Select(driver.findElement(By.id("unitType"))).selectByVisibleText("Wing");
	    driver.findElement(By.id("unitAssignment")).clear();
	    driver.findElement(By.id("unitAssignment")).sendKeys("102AW");
	    driver.findElement(By.id("unitAssignedNo")).click();
	    r.delay(5000); //notsure if i need
	    new Select(driver.findElement(By.id("assignmentStartDate.month"))).selectByVisibleText("January");
	    new Select(driver.findElement(By.id("assignmentStartDate.day"))).selectByVisibleText("01");
	    driver.findElement(By.id("assignmentStartDate.year")).clear();
	    driver.findElement(By.id("assignmentStartDate.year")).sendKeys("1998");
	    new Select(driver.findElement(By.id("assignmentEndDate.month"))).selectByVisibleText("January");
	    new Select(driver.findElement(By.id("assignmentEndDate.day"))).selectByVisibleText("01");
	    driver.findElement(By.id("assignmentEndDate.year")).clear();
	    driver.findElement(By.id("assignmentEndDate.year")).sendKeys("2002");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("personalAssault2")).click();
	    //driver.findElement(By.xpath("//form[@id='vnpForm']/div/fieldset/ul/li[3]/span/label")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("incidentDescription")).clear();
	    driver.findElement(By.id("incidentDescription")).sendKeys("test incident. Hurtful and traumatic experience");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("otherPeople1")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.linkText("*Add a Source of Information")).click();
	    r.delay(6000);
	    driver.findElement(By.id("name")).clear();
	    driver.findElement(By.id("name")).sendKeys("Capt Miller");
	    driver.findElement(By.id("address.addressLine1")).clear();
	    driver.findElement(By.id("address.addressLine1")).sendKeys("23 Shakerville");
	    driver.findElement(By.id("address.city")).clear();
	    driver.findElement(By.id("address.city")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("address.state"))).selectByVisibleText("Virginia");
	    driver.findElement(By.id("address.zipCode")).clear();
	    driver.findElement(By.id("address.zipCode")).sendKeys("20170");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("vetInfo.serviceInfo.otherBehaviorChanges")).clear();
	    driver.findElement(By.id("vetInfo.serviceInfo.otherBehaviorChanges")).sendKeys("substance abuse such as alcohol or drugs");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	}
	
	public static void createUnemployabilityBenefits(VDCFormTemplate formTemp){
		// Create Unemployability Benefit Forms
		deleteForm("Increased Compensation Based on Unemployability");
		driver.findElement(By.xpath("(//a[contains(text(),'Apply Now')])[6]")).click();
		logger.info("::Clicked on Unemployability Benefits Form ::");
		r.delay(10000);
	    driver.findElement(By.id("formInfo.privacyAccepted")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(15000);
	    driver.findElement(By.id("fileNumber")).clear();
	    driver.findElement(By.id("fileNumber")).sendKeys("60002332");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(15000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("medicalInfo.disabilities[1].preventsOccupation")).click();
	    driver.findElement(By.id("medicalEmploymentInfo.fullTimeAffectedDt")).clear();
	    driver.findElement(By.id("medicalEmploymentInfo.fullTimeAffectedDt")).sendKeys("01012002");
	    driver.findElement(By.id("medicalEmploymentInfo.disabledDt")).clear();
	    driver.findElement(By.id("medicalEmploymentInfo.disabledDt")).sendKeys("61012002");
	    driver.findElement(By.id("medicalEmploymentInfo.leftEmploymentInd1")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(8000);
	    driver.findElement(By.id("circumstances")).clear();
	    driver.findElement(By.id("circumstances")).sendKeys("test hurt and unable to work");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("veteran.medicalEmploymentInfo.retirementBenefitsInd1")).click();
	    driver.findElement(By.id("veteran.medicalEmploymentInfo.workersCompBenefitsInd1")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("veteran.medicalInfo.doctorsCarePast12Ind2")).click();
	    driver.findElement(By.id("veteran.medicalInfo.doctorsCarePast12Ind1")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.linkText("*Add a Doctor")).click();
	    r.delay(6000);
	    driver.findElement(By.id("physician.firstName")).clear();
	    driver.findElement(By.id("physician.firstName")).sendKeys("Alex");
	    driver.findElement(By.id("physician.lastName")).clear();
	    driver.findElement(By.id("physician.lastName")).sendKeys("Smith");
	    driver.findElement(By.id("location.addressLine1")).clear();
	    driver.findElement(By.id("location.addressLine1")).sendKeys("29 shims st");
	    driver.findElement(By.id("location.city")).clear();
	    driver.findElement(By.id("location.city")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("location.state"))).selectByVisibleText("Virginia");
	    driver.findElement(By.id("location.zipCode")).clear();
	    driver.findElement(By.id("location.zipCode")).sendKeys("20170");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.linkText("*Add Medical Treatment")).click();
	    r.delay(6000);
	    driver.findElement(By.id("treatmentStart")).clear();
	    driver.findElement(By.id("treatmentStart")).sendKeys("06012002");
	    driver.findElement(By.id("treatmentEnd")).clear();
	    driver.findElement(By.id("treatmentEnd")).sendKeys("12012012");
	    driver.findElements(By.xpath("//input[@name='disabilityIds']")).get(0).click();
	    driver.findElements(By.xpath("//input[@name='disabilityIds']")).get(1).click();
	    //driver.findElement(By.id("disabilityb9fbc481-4d3f-4ec8-bbde-3a42dac7a97b")).click();
	    //driver.findElement(By.id("disabilityb66d5e3c-effc-4f32-bebb-36213755d2af")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("veteran.medicalInfo.hospitalPast12Ind1")).click(); // check yes
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.xpath("//a[@class='btnLightGray']")).click();
	    r.delay(5000);
	    driver.findElement(By.id("hospitalTypeVAMC")).click();
	    r.delay(2000);
	    new Select(driver.findElement(By.id("treatmentCenterState"))).selectByVisibleText("Virginia");
	    r.delay(5000);
	    new Select(driver.findElement(By.id("corpTreatmentId"))).selectByVisibleText("HAMPTON VA MEDICAL CENTER");
	    driver.findElement(By.id("location.addressLine1")).clear();
	    driver.findElement(By.id("location.addressLine1")).sendKeys("291 vegas lane");
	    driver.findElement(By.id("location.zipCode")).clear();
	    driver.findElement(By.id("location.zipCode")).sendKeys("20170");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.xpath("//a[@class='btnLightGray']")).click();
	    r.delay(5000);
	    driver.findElement(By.id("treatmentStart")).clear();
	    driver.findElement(By.id("treatmentStart")).sendKeys("06012002");
	    driver.findElement(By.id("treatmentEnd")).clear();
	    driver.findElement(By.id("treatmentEnd")).sendKeys("12012012");
	    driver.findElements(By.xpath("//input[@name='disabilityIds']")).get(0).click();
	    driver.findElements(By.xpath("//input[@name='disabilityIds']")).get(1).click();
	    //driver.findElement(By.id("disability6d24a0df-d893-4af4-9e83-554d76f01b36")).click();
	    //driver.findElement(By.id("disability41d6cf91-2940-46fe-b1d4-d952ee2bb0ff")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("veteran.employmentInfo.searchedForEmployment1")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    /*driver.findElement(By.linkText("*Add an Employer")).click();
	    r.delay(5000);
	    driver.findElement(By.id("name")).clear();
	    driver.findElement(By.id("name")).sendKeys("IBM");
	    driver.findElement(By.id("address.addressLine1")).clear();
	    driver.findElement(By.id("address.addressLine1")).sendKeys("1500 computer blvd");
	    driver.findElement(By.id("address.city")).clear();
	    driver.findElement(By.id("address.city")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("address.state"))).selectByVisibleText("Virginia");
	    driver.findElement(By.id("address.zipCode")).clear();
	    driver.findElement(By.id("address.zipCode")).sendKeys("20170");
	    driver.findElement(By.id("workType")).clear();
	    driver.findElement(By.id("workType")).sendKeys("engineer");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("veteran.employmentInfo.employedPast51")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);*/
	    driver.findElement(By.linkText("*Add an Employer")).click();
	    r.delay(6000);
	    driver.findElement(By.id("name")).clear();
	    driver.findElement(By.id("name")).sendKeys("US Airforce");
	    driver.findElement(By.id("address.addressLine1")).clear();
	    driver.findElement(By.id("address.addressLine1")).sendKeys("100 Davidson lane");
	    driver.findElement(By.id("address.city")).clear();
	    driver.findElement(By.id("address.city")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("address.state"))).selectByVisibleText("Virginia");
	    driver.findElement(By.id("address.zipCode")).clear();
	    driver.findElement(By.id("address.zipCode")).sendKeys("20170");
	    driver.findElement(By.id("workType")).clear();
	    driver.findElement(By.id("workType")).sendKeys("engineer");
	    driver.findElement(By.id("appliedDt")).clear();
	    driver.findElement(By.id("appliedDt")).sendKeys("07012002");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);	    
	    driver.findElement(By.id("veteran.employmentInfo.employedPast51")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.linkText("*Add an Employer")).click();
	    r.delay(6000);
	    driver.findElement(By.id("name")).clear();
	    driver.findElement(By.id("name")).sendKeys("US Airforce");
	    driver.findElement(By.id("address.addressLine1")).clear();
	    driver.findElement(By.id("address.addressLine1")).sendKeys("100 Davidson lane");
	    driver.findElement(By.id("address.city")).clear();
	    driver.findElement(By.id("address.city")).sendKeys("Herndon");
	    new Select(driver.findElement(By.id("address.state"))).selectByVisibleText("Virginia");
	    driver.findElement(By.id("address.zipCode")).clear();
	    driver.findElement(By.id("address.zipCode")).sendKeys("20170");
	    driver.findElement(By.id("workType")).clear();
	    driver.findElement(By.id("workType")).sendKeys("engineer");
	    //driver.findElement(By.id("appliedDt")).clear();
	    //driver.findElement(By.id("appliedDt")).sendKeys("07012002");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("hoursPerWeek")).clear();
	    driver.findElement(By.id("hoursPerWeek")).sendKeys("40");
	    driver.findElement(By.id("startDt")).clear();
	    driver.findElement(By.id("startDt")).sendKeys("01012001");
	    driver.findElement(By.id("endDt")).clear();
	    driver.findElement(By.id("endDt")).sendKeys("06012002");
	    new Select(driver.findElement(By.id("timePeriod.timePeriod"))).selectByVisibleText("Month");
	    driver.findElement(By.id("timePeriod.timeLost")).clear();
	    driver.findElement(By.id("timePeriod.timeLost")).sendKeys("2");	    
	    driver.findElement(By.id("maxGrossPay")).clear();
	    driver.findElement(By.id("maxGrossPay")).sendKeys("100000");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);	    
	    driver.findElement(By.id("lastFullTime")).clear();
	    driver.findElement(By.id("lastFullTime")).sendKeys("06012002");
	    driver.findElement(By.id("maxGrossPay")).clear();
	    driver.findElement(By.id("maxGrossPay")).sendKeys("100000");
	    driver.findElement(By.id("yearRecieved")).clear();
	    driver.findElement(By.id("yearRecieved")).sendKeys("2002");
	    driver.findElement(By.id("workType")).clear();
	    driver.findElement(By.id("workType")).sendKeys("engineer");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("employmentInfo.lastYearsPay")).clear();
	    driver.findElement(By.id("employmentInfo.lastYearsPay")).sendKeys("30000");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    new Select(driver.findElement(By.id("educationInfo.highestEducation"))).selectByVisibleText("College - 4");
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("veteran.educationInfo.historyBeforeInd2")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("veteran.educationInfo.historyAfterInd2")).click();
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(6000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	    driver.findElement(By.id("btnNext")).click();
	    r.delay(5000);
	}
}//end of class.
